version: '3.9'
services:
  postgres:
    container_name: DB
    image: postgres:14.1-alpine
    environment:
      - PGUSER=root
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  backend:
    container_name: backend
    build:
      context: './Backend'
      dockerfile: './docker/backend/Dockerfile'
    volumes:
      - ./Backend:/usr/src/app
    depends_on:
      - postgres
    ports:
      - '3001:3001'

  seeder:
    container_name: seeder
    build:
      context: './Backend'
      dockerfile: './docker/seeder/Dockerfile'
    depends_on:
      - postgres
    command: npm run seed

  frontend:
    container_name: frontend
    build: './Frontend'
    volumes:
      - ./Frontend:/usr/src/app
    depends_on:
      - backend
      - postgres
      - seeder
    ports:
      - '3000:3000'

volumes:
  db:
    driver: local
